### ISSUE TITLE
answerモデルの作成

### ISSUE THREAD

**Issue by t-tonchim** [hr-dash/nazonazo_factory#10]
マイグレーションの制約とバリデーションもお願いします。
# TODO
### マイグレーション時の制約・型

---
#### answer_text
- [ ] t.string : not_null
### right_or_wrong
- [ ] boolean :not_null
### quiz_id
- [ ] quizsのidにFKつける
### バリデーション

---
#### answer_text
- [ ] length: { in: 1..30 }
- [ ] presence :true  
#### right_or_wrong
- [ ] presence :true  
- [ ] ４拓とかの時にtrueが必ず一つだけになるような制約つける  
  uniqueに　if　optionとか使ってメソッド作ったりとかでいけるかな？？
#### quiz_id
- [ ] belongs_to :quiz_id
- [ ] presence :true

**Comment by tomoyuki-tanaka** [comment]
# TODO
### マイグレーション時の制約・型
---
#### answer_text
 
### バリデーション
---
#### answer_text
- [ ] length: { in: 1..30 }
- [ ] presence :true  

#### right_or_wrong
- [ ] presence :true  

#### quiz_id
- [ ] belongs_to :quiz_id

**Comment by masahiro-yamazaki** [comment]
山崎担当

**Comment by masahiro-yamazaki** [comment]
rails generate model Answer answer_text:string right_or_wrong:boolean quiz:belongs_to

**Comment by masahiro-yamazaki** [comment]
以下のレビューをお願いします。
https://github.com/hr-dash/nazonazo_factory/pull/27
